/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import controller.Controller;
import model.HeaderTable;
import model.Invoice;

/**
 *
 * @author malek
 */
public class SigFrame extends javax.swing.JFrame {

    /**
     * Creates new form SalesInvoiceFrame
     */
    public SigFrame() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvHeaderTable = new javax.swing.JTable();
        InvHeaderTable.getSelectionModel().addListSelectionListener(listener);
        InvoiceNum = new javax.swing.JLabel();
        CustomerName = new javax.swing.JLabel();
        InvoiceDate = new javax.swing.JLabel();
        InvoiceTotal = new javax.swing.JLabel();
        CustNameLbl = new javax.swing.JLabel();
        invNumLbl = new javax.swing.JLabel();
        InvDateLbl = new javax.swing.JLabel();
        InvTotalLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvLineTable = new javax.swing.JTable();
        CreateInvBtn = new javax.swing.JButton();
        CreateInvBtn.addActionListener(listener);
        DeleteInvBtn = new javax.swing.JButton();
        DeleteInvBtn.addActionListener(listener);
        CreateItemBtn = new javax.swing.JButton();
        CreateItemBtn.addActionListener(listener);
        DeleteItemBtn = new javax.swing.JButton();
        DeleteItemBtn.addActionListener(listener);
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        loadItem = new javax.swing.JMenuItem();
        loadItem.addActionListener(listener);
        saveItem = new javax.swing.JMenuItem();
        saveItem.addActionListener(listener);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvHeaderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(InvHeaderTable);

        InvoiceNum.setText("Invoice Num");

        CustomerName.setText("Customer Name");

        InvoiceDate.setText("Invoice Date");

        InvoiceTotal.setText("Invoice Total");

        CustNameLbl.setText(".");

        invNumLbl.setText(".");

        InvDateLbl.setText(".");

        InvTotalLbl.setText(".");

        InvLineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(InvLineTable);

        CreateInvBtn.setText("Create Invoice");
        CreateInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateInvBtnActionPerformed(evt);
            }
        });

        DeleteInvBtn.setText("Delete Invoice");

        CreateItemBtn.setText("Create Item");

        DeleteItemBtn.setText("Delete Item");

        jMenu.setText("File");

        loadItem.setText("Load Files");
        jMenu.add(loadItem);

        saveItem.setText("Save Data");
        jMenu.add(saveItem);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerName)
                            .addComponent(InvoiceNum)
                            .addComponent(InvoiceDate)
                            .addComponent(InvoiceTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(invNumLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvTotalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(CreateInvBtn)
                .addGap(39, 39, 39)
                .addComponent(DeleteInvBtn)
                .addGap(100, 100, 100)
                .addComponent(CreateItemBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteItemBtn)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceNum)
                            .addComponent(invNumLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerName)
                            .addComponent(CustNameLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceDate)
                            .addComponent(InvDateLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceTotal)
                            .addComponent(InvTotalLbl))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateInvBtn)
                    .addComponent(DeleteInvBtn)
                    .addComponent(CreateItemBtn)
                    .addComponent(DeleteItemBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateInvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateInvBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SigFrame frame = new SigFrame();
                frame.setVisible(true);
                frame.listener.loadFiles("InvHeader.csv", "InvLine.csv");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateInvBtn;
    private javax.swing.JButton CreateItemBtn;
    private javax.swing.JLabel CustNameLbl;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JButton DeleteInvBtn;
    private javax.swing.JButton DeleteItemBtn;
    private javax.swing.JLabel InvDateLbl;
    private javax.swing.JTable InvHeaderTable;
    private javax.swing.JTable InvLineTable;
    private javax.swing.JLabel InvTotalLbl;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceNum;
    private javax.swing.JLabel InvoiceTotal;
    private javax.swing.JLabel invNumLbl;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadItem;
    private javax.swing.JMenuItem saveItem;
    // End of variables declaration//GEN-END:variables
    private Controller listener = new Controller(this);
    public static SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    private ArrayList<Invoice> invoices;
    private HeaderTable headerTableModel;

    public ArrayList<Invoice> getInvoices() {
        if (invoices == null) {
            invoices = new ArrayList<>();
        }
        return invoices;
    }

    public void setInvoices(ArrayList<Invoice> invoices) {
        this.invoices = invoices;
    }

    public HeaderTable getHeaderTableModel() {
        return headerTableModel;
    }

    public void setHeaderTableModel(HeaderTable headerTableModel) {
        this.headerTableModel = headerTableModel;
    }

    public JTable getInvoicesTable() {
        return InvHeaderTable;
    }

    public JTable getLinesTable() {
        return InvLineTable;
    }

    public JLabel getCustNameLabel() {
        return CustNameLbl;
    }

    public JLabel getInvDateLabel() {
        return InvDateLbl;
    }

    public JLabel getInvNumLabel() {
        return invNumLbl;
    }

    public JLabel getInvTotalLabel() {
        return InvTotalLbl;
    }

    public Controller getListener() {
        return listener;
    }
    
    
    
    
}
